services:
  back:
    image: ghcr.io/calaxo/opencv:latest
    container_name: opencv
    ports:
      - "5500:5500"
    restart: unless-stopped
    environment:
      DB_PATH: /app/data/database.sqlite
      NODE_ENV: production
      PORT: 5500
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
